# suppress inspection "UnusedProperty" for whole file
writer1=console
writer1.level=info
writer1.format=[test] {uptime: mm:ss.SSS} {level|min-size=5} {thread|min-size=20} {class-name|min-size=25} {message}
writer2=test debug log file
writer2.level=debug
writer2.format={date:yyyy-MM-dd HH:mm:ss.SSS} {level|min-size=5} {thread|min-size=40} {class-name|min-size=25} {message}
# We set the general level to debug so that the debug log file gets data.
# We can't merge tinylog configs in other modules, so using package-specific levels here would introduce coupling.
# It's ok to set the global level to debug because the console will still only get info level, and there are not a lot
# of debug logs apart from the places where we actually want them.
level=debug
