tasks:
  loop-task:
    action: !com.example.loopAction
      # direct loop between parameters
      p1: ${p2}
      p2: ${p1}

      # indirect loop: p4 refers to p5, and p5.sub refers to p4
      p4: ${p5}
      p5:
        sub: ${p6}
      p6: ${p4}

      # Accessing property on nullable hole
      p3: ${pluginSettings.nullableNested.x}
