/*
 * Copyright 2000-2026 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.
 */

package org.jetbrains.amper.frontend.plugins

import org.jetbrains.amper.frontend.SchemaEnum
import org.jetbrains.amper.frontend.api.CanBeReferenced
import org.jetbrains.amper.frontend.api.ConstInit
import org.jetbrains.amper.frontend.api.CustomSchemaDeclaration
import org.jetbrains.amper.frontend.api.DeprecatedSchema
import org.jetbrains.amper.frontend.api.ReadOnly
import org.jetbrains.amper.frontend.api.SchemaDoc
import org.jetbrains.amper.frontend.api.SchemaNode
import org.jetbrains.amper.frontend.api.Shorthand
import org.jetbrains.amper.frontend.api.StringSemantics
import org.jetbrains.amper.frontend.plugins.generated.ShadowClasspath
import org.jetbrains.amper.frontend.plugins.generated.ShadowCompilationArtifact
import org.jetbrains.amper.frontend.plugins.generated.ShadowDependencyLocal
import org.jetbrains.amper.frontend.plugins.generated.ShadowModuleSources
import org.jetbrains.amper.frontend.schema.Settings
import org.jetbrains.amper.frontend.types.SchemaType
import org.jetbrains.amper.plugins.schema.model.PluginData
import java.nio.file.Path

class PluginYamlRoot : SchemaNode() {
    @SchemaDoc("The tasks registered by this plugin. This is a map from task name to task registration data. " +
            "Task names are simple identifiers which are local to the plugin and are not required to be globally unique. " +
            "They are conventionally lowerCamelCase.")
    val tasks by value<Map<String, Task>>(default = emptyMap())

    @SchemaDoc("The checks registered by this plugin. Each check defines a custom checker " +
            "that can be invoked via the 'amper check' command.")
    val checks by value<List<CustomCheck>>(default = emptyList())

    @SchemaDoc("The commands registered by this plugin. Each command defines a custom command " +
            "that can be invoked via the 'amper do' command.")
    val commands by value<List<CustomCommand>>(default = emptyList())

    @SchemaDoc("Specifies generated entities to be contributed to the module's build.")
    val generated by nested<Generated>()

    @ReadOnly
    @SchemaDoc("Data from the module the plugin is enabled in")
    val module by value<ModuleDataForPlugin>()

    @ReadOnly
    @SchemaDoc("Data from the project within which the plugin is registered")
    val project by value<ProjectDataForPlugin>()

    @ReadOnly
    @CanBeReferenced
    val pluginSettings: PluginSettingsPlaceholder by value()
}

@CustomSchemaDeclaration
class PluginSettingsPlaceholder : SchemaNode()

/**
 * NOTE: We do not mark all the properties here as [ReadOnly] because the [PluginYamlRoot.module] is already marked.
 * So all these properties also cannot be set by the user.
 */
class ModuleDataForPlugin : SchemaNode() {
    @CanBeReferenced
    @SchemaDoc("Name of the module")
    val name by value<String>()

    @CanBeReferenced
    @SchemaDoc("Module's root directory (where `module.yaml` resides)")
    val rootDir by value<Path>()

    @CanBeReferenced
    @SchemaDoc("Runtime classpath of the module (jvm, main)")
    val runtimeClasspath by value<ShadowClasspath>()

    @CanBeReferenced
    @SchemaDoc("Compilation classpath of the module (jvm, main)")
    val compileClasspath by value<ShadowClasspath>()

    @CanBeReferenced
    @SchemaDoc("Kotlin and Java source directories of the module (jvm, main)")
    val kotlinJavaSources by value<ShadowModuleSources>()

    @CanBeReferenced
    @SchemaDoc("Resource directories of the module (jvm, main)")
    val resources by value<ShadowModuleSources>()

    @CanBeReferenced
    @SchemaDoc("Compiled JAR for the module (jvm, main)")
    val jar by value<ShadowCompilationArtifact>()

    @CanBeReferenced
    @SchemaDoc("Unpacked classes for the module (jvm, main)")
    val classes by value<ShadowCompilationArtifact>()

    @CanBeReferenced
    @SchemaDoc("Dependency on the module itself")
    val self by value<ShadowDependencyLocal>()

    @SchemaDoc("Module's `settings` configuration")
    val settings by value<Settings>()
}

class ProjectDataForPlugin : SchemaNode() {
    @CanBeReferenced
    @SchemaDoc("Project's root directory (where `project.yaml` resides if present)")
    val rootDir by value<Path>()
}

@CustomSchemaDeclaration
class TaskAction(
    val taskInfo: PluginData.TaskInfo,
) : SchemaNode()

class Task : SchemaNode() {
    @SchemaDoc("The task action definition. Requires a type specifier in the form of `!com.example.myTaskAction`, " +
            "where `com.example.myTaskAction` is the fully-qualified name of a `@TaskAction`-annotated " + 
            "function defined in plugin sources. " +
            "All the nested properties correspond to the chosen task action's parameters, and define the " +
            "values of the arguments.")
    val action by value<TaskAction>()

    @DeprecatedSchema("plugin.deprecated.mark.outputs.as")
    @SchemaDoc("The list of additional semantics specifiers for the task outputs. " +
            "If a task's output (e.g. generated sources) should be contributed back to the build, " +
            "add the corresponding entry to this list.")
    val markOutputsAs by value<List<MarkOutputAs>>(default = emptyList())

    @ReadOnly
    @CanBeReferenced
    @SchemaDoc("Dedicated task directory under the build root")
    val taskOutputDir by value<Path>()
}

abstract class FragmentScopedOutput : SchemaNode() {
    @SchemaDoc("A \"fragment\" descriptor defining the platform or main/test scope the generated files are " +
            "contributed to. " +
            "By default, the generated contents are associated with the main fragment in JVM-only modules, " +
            "or with the most common production fragment in multiplatform modules. This means that the " +
            "generated files are visible to all fragments by default.")
    val fragment: FragmentDescriptor by nested()
}

class MarkOutputAs : FragmentScopedOutput() {
    @SchemaDoc("The path to one of the task outputs. " +
            "It has to match one of the @Output-marked paths of the task action properties, " +
            "or a path nested in a @Output-marked object.")
    val path by value<Path>()

    @SchemaDoc("The kind of files that reside at the given path, which determines how they're going to be used in the build.")
    val kind by value<GeneratedPathKind>()
}

class FragmentDescriptor : SchemaNode() {
    @Shorthand
    @SchemaDoc("The fragment qualifier without the `@` symbol (e.g. `jvm`, `ios`, etc.), or the empty " +
            "string for the fragment that doesn't have a qualifier (this is the main fragment in " +
            "JVM-only modules, or the most common fragment in multiplatform modules, which means that the " +
            "generated files are visible transitively in all fragments of the module). " +
            "Empty string by default.")
    val modifier by value(default = "")

    @SchemaDoc("`true` to select a test fragment, `false` by default")
    val isTest by value(default = false)
}

class CustomCheck : SchemaNode() {
    @ConstInit
    @Shorthand
    @SchemaDoc("The name of the task that performs this check.")
    @StringSemantics(SchemaType.StringType.Semantics.TaskName)
    val performedBy by value<String>()

    @ConstInit
    @SchemaDoc("The name of this check. Defaults to the task name specified in 'performedBy'.")
    val name: String by referenceValue(::performedBy)
}

class CustomCommand : SchemaNode() {
    @ConstInit
    @Shorthand
    @SchemaDoc("The name of the task that performs this command.")
    @StringSemantics(SchemaType.StringType.Semantics.TaskName)
    val performedBy by value<String>()

    @ConstInit
    @SchemaDoc("The name of this command. Defaults to the task name specified in 'performedBy'.")
    val name: String by referenceValue(::performedBy)
}

class Generated : SchemaNode() {
    @SchemaDoc("Specifies generated source files to be compiled together with the module.")
    val sources: List<GeneratedSources> by value(default = emptyList())

    @SchemaDoc("Specifies generated resource files to be bundled together with the module.")
    val resources: List<GeneratedResources> by value(default = emptyList())

    @SchemaDoc("Specifies generated cinterop definition files to be processed and included in the build.")
    val cinteropDefinitions: List<GeneratedCInteropDefinition> by value(default = emptyList())
}

class GeneratedSources : FragmentScopedOutput() {
    @SchemaDoc("The language of the generated sources.")
    val language by value(default = GeneratedSourcesLanguage.Kotlin)

    @SchemaDoc("The directory containing the generated source files. " +
            "Must be an `@Output` of a task declared in this plugin.")
    val directory by value<Path>()
}

class GeneratedResources : FragmentScopedOutput() {
    @SchemaDoc("The directory containing the generated resource files. " +
            "Must be an `@Output` of a task declared in this plugin.")
    val directory by value<Path>()
}

class GeneratedCInteropDefinition : FragmentScopedOutput() {
    @SchemaDoc(
        "The `.def` file for the cinterop tool to process and include in the build. " +
                "Must be an `@Output` of a task declared in this plugin. " +
                "See [definition file format](https://kotlinlang.org/docs/native-definition-file.html) for reference."
    )
    val defFile by value<Path>()
}

enum class GeneratedSourcesLanguage(
    override val schemaValue: String,
) : SchemaEnum {
    @SchemaDoc("Kotlin source files")
    Kotlin("kotlin"),

    @SchemaDoc("Java source files")
    Java("java"),
}

enum class GeneratedPathKind(
    override val schemaValue: String,
) : SchemaEnum {
    @SchemaDoc("Kotlin sources to be compiled together with the module")
    KotlinSources("kotlin-sources"),

    @SchemaDoc("Java sources to be compiled together with the module")
    JavaSources("java-sources"),

    @SchemaDoc("Resources to be bundled together with the module")
    JvmResources("jvm-resources"),

    @SchemaDoc("Cinterop definition files to be picked up by the build")
    CinteropDefFile("cinterop-def-file"),
    ;

    override val outdated: Boolean
        get() = false
}