tasks:
  runCheckA:
    action: !org.jetbrains.amper.plugins.checker.runCheckA {}

checks:
  - performedBy: nonExistentTask
    name: badCheck

  - performedBy: runCheckA
    name: dynamic-check-${module.name}

  - performedBy: runCheckA
    name: ${project.rootDir}

  - performedBy: runCheckA
    name: badCheck